version: '3.9'

services:
  backend:
    build: ./backend
    container_name: docmind-api
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - LLM_PROVIDER=${LLM_PROVIDER}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - OLLAMA_EMBED_MODEL=${OLLAMA_EMBED_MODEL}
    depends_on:
      - chromadb
    networks:
      - docmind-network

  chromadb:
    image: chromadb/chroma:latest
    container_name: docmind-chroma
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    networks:
      - docmind-network

networks:
  docmind-network:
    driver: bridge
